#!/usr/bin/env bash

function create_cluster() {
  gcloud beta dataproc clusters create ggcd-g9-tp2 \
    --region us-central1 --zone us-central1-c \
    --master-machine-type n1-standard-4 \
    --num-workers 2 \
    --master-boot-disk-size 500 \
    --worker-machine-type n1-standard-4 \
    --worker-boot-disk-size 500 \
    --image-version 2.0-debian10 \
    --project ggcd-grupo-9
}

gcloud beta compute ssh \
    --zone "us-central1-f" "ggcd-g9-tp2-m" \
    --project "ggcd-grupo-9" -- <data/import_data.sh

gcloud beta compute ssh \
  --zone "us-central1-f" "ggcd-g9-tp2-m" \
  --project "ggcd-grupo-9" -- hdfs dfs -ls /

gcloud beta compute ssh \
  --zone "us-central1-f" "ggcd-g9-tp2-m" \
  --project "ggcd-grupo-9" -- <data/create_tables.sh

